name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stable-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
          - name: macos-latest
          - name: windows-latest

    runs-on: ${{ matrix.os.name }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os.name != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install on windows
        if: ${{ matrix.os.name == 'windows-latest' }}
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Setup MSVC
        if: ${{ matrix.os.name == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: moon update

      - name: moon check
        run: moon check --deny-warn

      - name: moon info
        run: |
          moon info
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
      
      - name: moon test
        run: |
          moon test --target all --serial
          moon test --target all --serial --release
          